### ISSUE TITLE
Assertion Failure on Wallhack validation check

### ISSUE THREAD

**Issue by SM91337** [L-EARN/NoCheatZ-4#38] opened 2016-06-20 03:06 UTC
[Line 103 (WallhackBlocker.h) ](https://github.com/L-EARN/NoCheatZ-4/blob/master/server-plugin/Code/Systems/Blockers/WallhackBlocker.h#L103)

Crash: http://puu.sh/pyZDR/49cac01027.png

Reproduction: Join server when another player is already in server or when playing against a bot, let the bot kill you.

**Comment by L-EARN** [comment] 2016-06-20 04:48
Hi,

I will need a stack trace for this one please, just to know if this caused by weapons or players. (It is unlikely to be caused by players though)

Thanks.

**Comment by SM91337** [comment] 2016-06-20 05:07
Hi, how would I get the stacktrace? 

Do you have steam?

**Comment by L-EARN** [comment] 2016-06-20 05:15
Of course I have steam.

To get the stack trace you must run the server with visual studio and hit the Retry button when you have the assertion.

Or you could try to build this branch and tell me if this corrects the issue : https://github.com/L-EARN/NoCheatZ-4/tree/WallhackBlocker-fix

**Comment by SM91337** [comment] 2016-06-20 05:18
I will give the other branch a test because I don't have a local server setup, i am running the module on a dedicated server.

This is my steam: http://steamcommunity.com/id/sm91337/ It would be easier to correspond over that if you want.

**Comment by SM91337** [comment] 2016-06-20 05:47
The issue appears to be fixed, I will run the plugin on all my gameservers (which will fill up with players later) now to asses the performance / find any other bugs.

**Comment by SM91337** [comment] 2016-06-20 05:53
Okay, that failed, one of my servers crashed already :(

Crash dump: http://puu.sh/pz7Cu/aa5e96833d.dmp

**Comment by L-EARN** [comment] 2016-06-20 07:46
Please test with the latest code from https://github.com/L-EARN/NoCheatZ-4/tree/WallhackBlocker-fix
I've updated it.

Also don't send me crash dumps.

**Comment by L-EARN** [comment] 2016-06-20 11:24
Changes to WallhackBlocker-fix and AntiFlashbangBlocker fix have been merged to the branch dev-opt then removed.

So if you want to test those changes, please compile the branch dev-opt.

If you ever ever insist sending me crash dumps, please give me the .pdb and the.dll files with it.

Additionnaly, I recommend you to run your server with WinDbg if you know there is bugs. This way you will get stack traces without having to set up visual studio on your server.

Thanks.

**Closed** 2016-06-21 05:27 UTC
Labels: AllOS, confirmed, CS:GO
