### ISSUE TITLE
Interesting ban

### ISSUE THREAD

**Issue by TR1D** [L-EARN/NoCheatZ-4#169] opened 2017-07-19 20:05 UTC
Dedicated csgo server, steam, no mods
NoCheatZ v4 r10, debian

It looks like the player folded the game at the time of the ban, and his ping in that moment was to high >300.

[Demo](http://dl.awp.by/auto-AWP-071817-211216-awp_lego_2_r.zip)

```07/18/17 21:25:59 [ Server Tick #108803, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #105344 ] EyeAnglesTester triggered a detection : TRASTER [STEAM_1:1:215078988 - 176.59.73.209:20169] is using a No recoil.
07/18/17 21:25:59 [ Server Tick #108803, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #105344 ] v4-r10
07/18/17 21:25:59 [ Server Tick #108803, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #105344 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 265.697998,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 1
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/18/17 21:26:04 [ Server Tick #109381, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #105922 ] EyeAnglesTester triggered a detection : TRASTER [STEAM_1:1:215078988 - -] is using a No recoil.
07/18/17 21:26:04 [ Server Tick #109381, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #105922 ] v4-r10
07/18/17 21:26:04 [ Server Tick #109381, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #105922 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 265.697998,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 290
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/18/17 21:26:08 [ Server Tick #109959, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #106500 ] EyeAnglesTester triggered a detection : TRASTER [STEAM_1:1:215078988 - -] is using a No recoil.
07/18/17 21:26:08 [ Server Tick #109959, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #106500 ] v4-r10
07/18/17 21:26:08 [ Server Tick #109959, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #106500 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 265.697998,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 579
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/18/17 21:26:09 [ Server Tick #110085, SourceTV:addons/sourcemod/data/demos/auto-AWP-071817-211216-awp_lego_2_r.dem : Tick #106626 ] Player disconnect : TRASTER [STEAM_1:1:215078988] -> Reason : Kicked by Console : [NoCheatZ 4] Banned by NoCheatZ 4 : No recoil detection with EyeAnglesTester ```

**Comment by L-EARN** [comment] 2017-07-19 20:13
Oh wait. That's not supposed to detect with this data.
There is a bug.

**Comment by TR1D** [comment] 2017-07-19 20:19
A similar case
[Demo](http://dl.awp.by/auto-AWP-071917-224821-awp_lego_x.rar)
```07/19/17 22:49:08 [ Server Tick #8117, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #6022 ] EyeAnglesTester triggered a detection : Мастер Кабан [STEAM_1:1:86950419 - -] is using a Anti-Aim.
07/19/17 22:49:08 [ Server Tick #8117, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #6022 ] v4-r10
07/19/17 22:49:08 [ Server Tick #8117, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #6022 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 1
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/19/17 22:49:13 [ Server Tick #8695, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #6600 ] EyeAnglesTester triggered a detection : Мастер Кабан [STEAM_1:1:86950419 - -] is using a Anti-Aim.
07/19/17 22:49:13 [ Server Tick #8695, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #6600 ] v4-r10
07/19/17 22:49:13 [ Server Tick #8695, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #6600 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 290
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/19/17 22:49:17 [ Server Tick #9271, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #7176 ] EyeAnglesTester triggered a detection : Мастер Кабан [STEAM_1:1:86950419 - -] is using a Anti-Aim.
07/19/17 22:49:17 [ Server Tick #9271, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #7176 ] v4-r10
07/19/17 22:49:17 [ Server Tick #9271, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #7176 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 578
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/19/17 22:49:18 [ Server Tick #9398, SourceTV:addons/sourcemod/data/demos/auto-AWP-071917-224821-awp_lego_x.dem : Tick #7303 ] Player disconnect : Мастер Кабан [STEAM_1:1:86950419] -> Reason : Kicked by Console : [NoCheatZ 4] Banned by NoCheatZ 4 : Anti-Aim detection with EyeAnglesTester
```

**Comment by TR1D** [comment] 2017-07-19 20:21
Can I get more information about false positives with this data ?

**Comment by L-EARN** [comment] 2017-07-19 20:35
The CSGO engine is a bit special. It replays to last CUserCmd of the player when there is a loss.

And so when this command is replayed, the server also have to do interpolation with angles (euler angles), potentially making angles out of bounds.
The principle of this tester is to detect old aimbots that also introduced out of bounds aimbots .. (In reality this detection is very old and mostly patched by all cheat providers now).

The last time, I tried to prevent this by only detect if : 
- The current angle is out of bounds
- The angle of the previous CUserCmd was also out of bounds 
- Both angles are not equal 

So the player has to send 2 differents, still out of bounds angles to trigger a detection.
And as you can see in the data the angles are the same ...

Unfurtunately I introduced errors while fixing the code. (You should be aware I make a lot of regressions at the moment ...)

**Comment by L-EARN** [comment] 2017-07-19 21:15
Should be fixed in r12.

**Comment by TR1D** [comment] 2017-07-21 16:12
r14 still try to ban for afk.
[Demo](http://dem.awp.by/demos/170721/auto-AWP-072117-151835-awp_indiaNG.zip)
```
07/21/17 15:26:24 [ Server Tick #62020, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #59992 ] EyeAnglesTester triggered a detection : Yolo_God [STEAM_1:1:217029502 - 5.18.206.232:37601] is using a Anti-Aim.
07/21/17 15:26:24 [ Server Tick #62020, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #59992 ] v4-r14
07/21/17 15:26:24 [ Server Tick #62020, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #59992 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 321
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/21/17 15:26:29 [ Server Tick #62660, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #60632 ] EyeAnglesTester triggered a detection : Yolo_God [STEAM_1:1:217029502 - 5.18.206.232:37601] is using a Anti-Aim.
07/21/17 15:26:29 [ Server Tick #62660, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #60632 ] v4-r14
07/21/17 15:26:29 [ Server Tick #62660, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #60632 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 641
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/21/17 15:26:45 [ Server Tick #64708, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #62680 ] EyeAnglesTester triggered a detection : Yolo_God [STEAM_1:1:217029502 - 5.18.206.232:37601] is using a Anti-Aim.
07/21/17 15:26:45 [ Server Tick #64708, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #62680 ] v4-r14
07/21/17 15:26:45 [ Server Tick #64708, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #62680 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 747
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/21/17 15:26:50 [ Server Tick #65348, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #63320 ] EyeAnglesTester triggered a detection : Yolo_God [STEAM_1:1:217029502 - 5.18.206.232:37601] is using a Anti-Aim.
07/21/17 15:26:50 [ Server Tick #65348, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #63320 ] v4-r14
07/21/17 15:26:50 [ Server Tick #65348, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #63320 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 1067
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/21/17 15:26:55 [ Server Tick #65988, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #63960 ] EyeAnglesTester triggered a detection : Yolo_God [STEAM_1:1:217029502 - 5.18.206.232:37601] is using a Anti-Aim.
07/21/17 15:26:55 [ Server Tick #65988, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #63960 ] v4-r14
07/21/17 15:26:55 [ Server Tick #65988, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #63960 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 1387
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/21/17 15:27:00 [ Server Tick #66628, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #64600 ] EyeAnglesTester triggered a detection : Yolo_God [STEAM_1:1:217029502 - 5.18.206.232:37601] is using a Anti-Aim.
07/21/17 15:27:00 [ Server Tick #66628, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #64600 ] v4-r14
07/21/17 15:27:00 [ Server Tick #66628, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #64600 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 1707
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/21/17 15:27:05 [ Server Tick #67268, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #65240 ] EyeAnglesTester triggered a detection : Yolo_God [STEAM_1:1:217029502 - 5.18.206.232:37601] is using a Anti-Aim.
07/21/17 15:27:05 [ Server Tick #67268, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #65240 ] v4-r14
07/21/17 15:27:05 [ Server Tick #67268, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #65240 ] :::: EyeAngleInfo {
:::::::: EyeAngleX {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: },
:::::::: EyeAngleY {
:::::::::::: Angle : 270.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 2027
:::::::: },
:::::::: EyeAngleZ {
:::::::::::: Angle : 0.000000,
:::::::::::: Previous Angle : 0.000000,
:::::::::::: Detections Count : 0
:::::::: }
:::: }
07/21/17 15:27:06 [ Server Tick #67426, SourceTV:addons/sourcemod/data/demos/auto-AWP-072117-151835-awp_indiaNG.dem : Tick #65398 ] Player disconnect : Yolo_God [STEAM_1:1:217029502] -> Reason : Yolo_God timed out
```

**Comment by L-EARN** [comment] 2017-07-21 23:09
I got a hard time debugging why this happen.

It seems to be a memory alignement issue.

Now I tested it using the setang command and the detection works as expected. This will be fixed for the next release.

**Closed** 2017-07-22 00:28 UTC
Labels: g:AllGames, o:AllOS, s:confirmed, t:False Detection
