### ISSUE TITLE
Not load on linux

### ISSUE THREAD

**Issue by rsgua** [L-EARN/NoCheatZ-4#75] opened 2016-07-25 23:08 UTC
Not load on linux. Plugin want load on linux server. Game CS:GO.

**Comment by L-EARN** [comment] 2016-07-26 04:44
Hi,

Can you copy the error messages, if any, you have in logs (csgo/logs/NoCheatZ_4_Logs/) please ?
Or the error message you have in console.

Thanks.

**Comment by rsgua** [comment] 2016-07-27 15:54
07/27/16 11:52:58 [ Server Tick #0] ERROR : ConfigManager::GetIniAttributeValue : Cannot find root CONFIG
07/27/16 11:52:58 [ Server Tick #0] ERROR : ConfigManager::GetIniAttributeValue : Cannot find attribute CONFIG -> config_version
07/27/16 11:52:58 [ Server Tick #0] ERROR : ConfigManager::LoadConfig failed

**Comment by L-EARN** [comment] 2016-07-27 16:43
Hi,

This is a duplicate of the issue #74 

Just change the line endings of the config.ini file from CRLF to LF.

Here is a solution to do it : http://stackoverflow.com/a/19283453

I'm will push another build in less than 2 hour.

**Closed by L-EARN** 2016-07-27 16:43 UTC
Labels: duplicate
