### ISSUE TITLE
[Issue] False Ban? | No Block WH, No block Anti-Flash

### ISSUE THREAD

**Issue by BlackYuzia** [L-EARN/NoCheatZ-4#187] opened 2017-07-29 09:38 UTC
@L-EARN 
Game: CS:GO
Mods: SM, MM, Public.
Type: Steam/No-Steam Server

Now, I see banned players by that reason:
"Banned by NoCheatZ 4 : Tempered UserCmd detection with BadUserCmdTester"
In logs I find that: 
> 07/29/17 11:13:06 [ Server Tick #61413] ConVarTester triggered a detection : pro100 Hulumulu [STEAM_1:0:648929367 - 176.100.79.200:27005] is using a r_showenvcubemap ConVar request time out.
> 07/29/17 11:13:06 [ Server Tick #61413] v4-r49-0-g42fba11
> 07/29/17 11:13:06 [ Server Tick #61413] :::: CurrentConVarRequest {
> :::::::: Request Status : SENT,
> :::::::: Request Sent At : 4213.615723,
> :::::::: Attempts : 6,
> :::::::: ConVarInfo {
> :::::::::::: ConVar Name : r_showenvcubemap,
> :::::::::::: Expected Value : 0,
> :::::::::::: Got Value : NO ANSWER - TIMED OUT,
> :::::::::::: Answer Status : NO STATUS,
> :::::::::::: Comparison Rule : SAME
> 
Problem = TimeOut?
If that NO-STEAM Client, and he not have/not wrote that CMD?

Now, other problem with Block WH and Block Anti-Flash and Block anti-Smoke
I pinned screenshots. If you not trust me.
I do not know WHY that func. not work.
If you know how fix that, pls fix. 
Thanks.

![de_dust20020](https://user-images.githubusercontent.com/25010528/28743763-aaaf7f6e-745a-11e7-9fea-6676084ce99a.jpg)
![de_dust20016](https://user-images.githubusercontent.com/25010528/28743765-aab027fc-745a-11e7-985c-633dea820fa4.jpg)
![de_dust20013](https://user-images.githubusercontent.com/25010528/28743764-aab00b00-745a-11e7-808e-c54d7e68b9c9.jpg)
![de_dust20021](https://user-images.githubusercontent.com/25010528/28743766-aab02810-745a-11e7-8981-0680fcfdaf37.jpg)
![20170729113404_1](https://user-images.githubusercontent.com/25010528/28743767-aab5d6d4-745a-11e7-91b5-e8294f010620.jpg)

**Comment by L-EARN** [comment] 2017-07-29 10:39
Hi,

Thank you for reporting this.

I'll look for the cusercmd false detection.

Now for convartester, I still don't know what is the reason for this. I fixed every possible error I could find (see #168). The only reason I can think of now is that you use another plugin that is stealing the convar requests from nocheatz. 

Obviously the anti wallhack won't work for wallhacks that are based on sound and radar.
The only thing anti wallhack, flashbang and smoke does is to stop transmitting entities. It doesn't mean antismokeblocker will force the smoke to appear. It simply stop transmitting players behind the smoke.

Test it with a simple r_drawothermodels 2 wallhack, or with r_drawparticles 0, you'll see it works for this one. 

But for sound based wallhacks or radar hacks there is not any plan to prevent this, even though the systems will work if players are in the same PVS.

**Comment by L-EARN** [comment] 2017-07-29 11:19
Is your server running under windows or linux ?

**Comment by BlackYuzia** [comment] 2017-07-29 13:36
@L-EARN Linux

**Comment by BlackYuzia** [comment] 2017-07-29 13:39
@L-EARN oh, okey. I think WH BLOCK = WH BLOCK :D
Oh, and you know anti-cheat: Ultra SMAC? / SMAC ULTR@
That AC (Anti-Cheat) Have Full block WH. If you ask a Creator this AC, about that. Maybe he give you idea how you can block WH, flash, smoke hacks and others?

**Comment by L-EARN** [comment] 2017-07-29 13:45
I only got troubles dealing with the radar of CSGO. It's more advanced than the one we got in CS:S + harder to reverse because they stripped symbols now. It changed a lot.

I think it's easier to start working against sound esp before. I was just too lazy to implement it yet.

**Comment by BlackYuzia** [comment] 2017-07-29 14:06
@L-EARN  We believe in you  :+1:

**Comment by hooliganxxx** [comment] 2017-07-29 18:31
Hi there, 

I have the same issue with Tempered UserCmd detection with BadUserCmdTester. 

It banned some people on my server that I know for sure are not hackers - the one was playing right next to me (I mean same physical room) when he got banned - all of them are steam players. 

Is there a way to disable this tester before it works  properly?  Apparently it bans much more often than other testers, and judging by these two instances I can't be sure whether those are valid bans. For now I have disabled radarhackblocker, bunnyhop blocker and autotv recording. The stats for bans you can find at csgo.cs-derzkiy.ru 

If you could, please explain the logic behind that tester - at least what it checks for.

The one more thing I noticed, the antiflash entities are not being blocked properly. I will try and record a video for that, but they get appearing and disappearing - of course making the game not comfortable for cheaters, however still interfering with honest players.

**Comment by BlackYuzia** [comment] 2017-07-29 19:17
Example:
```
ncz ConCommandTester disable
ncz ConCommandTester SetAction BAN_NOW

ncz BadUserCmdTester disable
ncz BadUserCmdTester SetAction BAN_NOW

ncz ConVarTester disable
ncz ConVarTester SetAction BAN_NOW
```

@hooliganxxx try disabled/enabled func. CMD, or disabled only:
ncz ConVarTester disable

Oh, and time ban. You can change it
(0 = Permanent; 0> time in Min.)
Cvar:
`
ncz BanRequest SetBanTime 0
`
If you not know right banned players or not. you can disabled ban/kick
use that cvars:
```
ncz BanRequest CanKick Yes
ncz BanRequest CanBan Yes
```
Now, There's all what we can do it.
Wait fix and Updates.

If you want know how that work. Call to @L-EARN

**Comment by hooliganxxx** [comment] 2017-07-29 21:28
Btw, I was thinking about this and what's in common - both of these bans got after the 
 guys killed someone and started defusing the bomb (that's when they got banned and kicked from the server). Maybe the bomb has to do something with it.

**Comment by hooliganxxx** [comment] 2017-07-30 12:18
Thanks for the updates, I will be able to comment on those later tonight.

**Comment by L-EARN** [comment] 2017-07-30 12:20
It's not yet released. I'm fixing other things in dev2. Currently fixing a regression with WallhackBlocker.

**Comment by L-EARN** [comment] 2017-07-30 14:04
r58 released.

I'm closing this issue because the main things should be fixed.

@BlackYuzia @hooliganxxx 
I prefer that you open multiple different issue threads, because inserting issues inside one thread doesn't help me organize better my work. Thank you.

**Closed by L-EARN** 2017-07-30 14:04 UTC
